### PR TITLE
Fix missing extension icons

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Assembly is strong signed again.
- Add new targets to process image manifest.

## Motivation and Context
- Following investigation and instructions kindly provided by @softworkz.
- Resolves nanoFramework/Home#1009.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by josesimoes** [comment]
@softworkz hopefully I've followed your instructions correctly.
Unfortunately the extension can't run, I suspect because of the ProvideCodeBase attribute... 
I get this:


```
SetSite failed for package [Visual Studio 2022 extension for .NET nanoFramework. Enables creating C# Solutions to be deployed to a target board and provides debugging tools.] Source: 'nanoFramework.Tools.VS2022.Extension' Description: Unable to load file or assembly 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=0ffbc31322e9d308' or one of its dependencies. The system could not locate the specified file.
System.IO.FileNotFoundException: Unable to load file or assembly 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=0ffbc31322e9d308' or one of its dependencies. The system could not locate the specified file.
File name: 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=0ffbc31322e9d308'
   at nanoFramework.Tools.VisualStudio.Extension.NanoFrameworkPackage.<InitializeAsync>d__93.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.StartTStateMachine
   at nanoFramework.Tools.VisualStudio.Extension.NanoFrameworkPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()>
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ........
```

**Comment by softworkz** [comment]
Is your dll which provides the images signed with a strong name key? This can have a viral effect IIRC (haven't used it for a while).

The attribute doesn't do much it just collects some information about your dll which then gets put into the pkgdef. It also have some methods to help VS to register the package automatically, so I can't say whether it would work when you:

- Compile once with attribute
- Make a copy of pkgdef
- Compile without attribute
- Open the vsix and edit the pkgdef so it looks like before

I don't think though, that the attribute has any effect on other assemblies, because the attribute is specific to the VSPS/SPS, not known anywhere else...

**Comment by softworkz** [comment]
Also: 

- The main project dll (which exports the project definition should be at the root of thee package
- The imagemanifest must be at the root as well (name doesn't need to equal the dll name, you can have multiple)
- The imagemanifest must be set to "Include in VSIX" (unzip the VSIX and check)
- After unzipping, you could try to open the dll in dotPeek, then open the References node and see whether some references are unresolved (VS and framework dlls are ok to be unresolved, but not any others)

**Comment by josesimoes** [comment]
Yes, I've added back strong signing as suggested.
Loading with dotPeek (with or without `ProvideCodeBase`), I can see the resources and the references are all available
image

**Comment by josesimoes** [comment]
Commenting out `ProvideCodeBase` does allow the extension to load and I can see the icons in experimental instance.
But I've seen this before and the icons not showing on release after a random time, so I can't say for sure... 😞

**Comment by josesimoes** [comment]
I guess I'll try a release with these changes and see how it goes.

**Comment by josesimoes** [comment]
For reference:

- [x]  The main project dll (which exports the project system should be at the root of thee package
- [x] The imagemanifest must be at the root as well (name doesn't need to equal the dll name, you can have multiple)
- [x] The imagemanifest must be set to "Include in VSIX" (unzip the VSIX and check)

**Comment by softworkz** [comment]
> Commenting out ProvideCodeBase does allow the extension to load 

Is it the attribute or the strong name signing? Because - IIRC - signing prevents the assembly from loading unsigned assemblies.  If you cannot sign all the assemblies which need to be loaded, you could try the following:

- Create an additional VSPackage, i.e. an additional C# project - only for the images
- Apply the things I mentioned to that assembly only, incl. snk signing
- The image assembly must not reference anything non-framework or non-VSSDK assemblies
- Then, your other (unsigned) assemblies can reference the image assembly
  That's the direction which works, but a signed assembly is not allowed to load an unsigned one

My solution is rather barebones at this time, while yours is pretty loaded, so isolating the image part might make sense. 
In all my tests, the behavior was very consistent, I haven't seen any variations; with the manifest authored as intended, it works, and without, it doesn't.

One theory I have about why it might not be deterministic  is that on systems where you are seeing this, there were earlier installations of your extension, installed before VS broke it. As mentioned in the article, VS must have some mechanism to still allow "Pattern A" for not-yet-updated extensions. 
If I'm right, they have designed this primarily for their own extensions, which are installed as part of Visual Studio.  Maybe they are doing a date check or a "modified-from-original-file" check or something.
The final part of that theory is that newer versions of extensions are not allowed without using Pattern B, and that when users are running those 'reset' or cleanup' commands as suggested, VS might restore some config or file data (about your extension) which was from an earlier time, i.e. before they introduced Pattern B., and hence they would waive your extension to still allow Pattern A.  Once a user updates the plug (or something else that is related, VS might consider it as a new extension and doesn't allow image loading.

I don't have any previously installed CPS extension which I could use for testing, but I mentioned some key points for the theory above which you should be able to confirm or bust easily, from all the painful experience you had with this ;-)

**Comment by josesimoes** [comment]
@softworkz It's only the attribute. The strong signing is there again.

I'm at loss too... the behavior is quite random. It can be OK for months, with or without installing any other extension, install a new VS release, sometimes that makes the icons show up again. And all the suden, one opens VS one day an no more icons... Rather frustrating. 

Anyway, I'll publish as it is now and provide feedback on the Home issue.
Thank you again for your time and insights!

**Comment by softworkz** [comment]
For reference, I have created a new project system - a 10-Minute job with the patched Extensibility Extension for 2023.

I added the "Custom Icons" temßplate, replaced the image with one which catches common attention
I added the ProjecTreePropertiesProvider item template and made it

**Comment by vsoldatkin** [comment]
> @softworkz hopefully I've followed your instructions correctly. Unfortunately the extension can't run, I suspect because of the ProvideCodeBase attribute... I get this:
> 
> ```
> SetSite failed for package [Visual Studio 2022 extension for .NET nanoFramework. Enables creating C# Solutions to be deployed to a target board and provides debugging tools.] Source: 'nanoFramework.Tools.VS2022.Extension' Description: Unable to load file or assembly 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=0ffbc31322e9d308' or one of its dependencies. The system could not locate the specified file.
> System.IO.FileNotFoundException: Unable to load file or assembly 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=0ffbc31322e9d308' or one of its dependencies. The system could not locate the specified file.
> File name: 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=0ffbc31322e9d308'
>    at nanoFramework.Tools.VisualStudio.Extension.NanoFrameworkPackage.<InitializeAsync>d__93.MoveNext()
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.StartTStateMachine
>    at nanoFramework.Tools.VisualStudio.Extension.NanoFrameworkPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
>    at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()>
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
>    at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ........
> ```
> 
> Any thoughts/suggestions on the above please? 😅

I'm experiencing the same error after updating the extension to 2022.3.0.66 on VS 2022 17.8.1.

**Comment by vsoldatkin** [comment]
As far as I understand, the GalaSoft.MvvmLight project is not maintained anymore, and it is suggested to migrate to the Microsoft library https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/

**Comment by josesimoes** [comment]
> As far as I understand, the GalaSoft.MvvmLight project is not maintained anymore, and it is suggested to migrate to the Microsoft library https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/

That is correct. If you want to take a look into tackling this, it would be much appreciated! 😃

**Pull request merged**
