### PR TITLE
Remove unused changelog file

### PR DESCRIPTION
**Pull request by networkfusion**
## Motivation and Context
VS2022 changelog not being generated.
Orignal changelog.md was over 3 years old, so removed.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
Yes. The original one (when there was only VS2017) wasn't doing nothing on the repo.
Now for the VS2022 one, it has not being generated because there was no gtihub release published.

**Comment by CZEMacLeod** [comment]
This file is still linked and referenced from the extensions UI in visual studio. It would be nice to be able to see what the changes are when updating.
image

**Comment by CZEMacLeod** [comment]
It also seems to be referenced from the releases section e.g.
https://github.com/nanoframework/nf-Visual-Studio-extension/releases/tag/v2022.2.0.35

**Comment by josesimoes** [comment]
@CZEMacLeod 👀 nanoframework/Home/#1133

**Pull request merged**
