### PR TITLE
Improve popup message when run without debug

### PR DESCRIPTION
**Pull request by hicham-barhoumi**
## Description

Improve popup "Hello from LaunchSuspended!" when run without debug.

## How Has This Been Tested?

With test extension

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by josesimoes** [comment]
@hicham-barhoumi this pop-up is there on purpose, to help debug situations where the use tries to start a debug session on a unsupported way. 
Wondering if you are seeing this message in any specific situation of your daily usage?

**Comment by hicham-barhoumi** [comment]
@josesimoes I have it every time i run "Execute without debug" "ctrl+F5" it is annoying,
if it is for debug purposes we condition it for debug environment, but for a simple user it does not give confidence in the extension and it will not help him in any way, he will never understand the meaning.

**Comment by josesimoes** [comment]
@hicham-barhoumi reason for this is that this feature is not supported. OK it deploys the application, but it does NOT start it. One has to hit reset in order for that to happen.
Without the reset this is equivalent to execute the DEPLOY command.

I can see two ways to "fix" this:
1. Implement the necessary calls to reset the device.
2. Replace the message instructing the user that a reset is needed in order to run the app.

**Comment by hicham-barhoumi** [comment]
Okay this is more clear now, i ll change the message to be more suited, i m new so i m not very sure to that i can dot the device reset

**Comment by josesimoes** [comment]
That's the most straightforward approach, yes. 
Suggest something similar to "Deployment successful, please reset the nano device to get the application running".

**Review by josesimoes — APPROVED** [review]
LGTM!

**Pull request merged**
